### ISSUE TITLE
Format csv nie działa

### ISSUE THREAD

**Issue by o2droid** [mlesniew/elicznik#10]
Cześć,

Przy próbie zapisania pliku jako csv (opcja format=csv) skrypt wyrzuca błąd:
Traceback (most recent call last):
  File "/usr/local/bin/elicznik", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/elicznik/__main__.py", line 68, in main
    for timestamp, consumed, produced in result:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)

Korzystam z python 3.11.

**Comment by mlesniew** [comment]
Rzeczywiście!  

Poprawiłem to -- teraz wersja z mastera powinna działać dobrze.  Wkrótce wrzucę nową wersję na pypi.

**Comment by o2droid** [comment]
Dzięki, działa :)
