### ISSUE TITLE
Mały problem

### ISSUE THREAD

**Issue by magicsoft75** [mlesniew/elicznik#15]
Cześć, dzięki za skrypt ale proszę o pomoc - coś nie mogę go uruchomić.
Czy on jest kompatybilny z nową wersją strony Taurona?

**Comment by mlesniew** [comment]
Tak, skrypt powinien działać.  W czym jest problem, pojawia się jakiś błąd?

**Comment by magicsoft75** [comment]
Tak, pojawia się błąd:  
File "/home/pi/.local/bin/el.py", line 10, in <module>
    for timestamp, consumed, produced in readings:
ValueError: too many values to unpack (expected 3)

**Comment by mlesniew** [comment]
`/home/pi/.local/bin/el.py` nie wygląda na część paczki elicznik.  Tak czy siak, błąd pewnie polega na tym, że `readings` ma pięć wartości, a nie 3: timestamp, konsumpcja, produkcja, konsumpcja netto, produkcja netto.

**Comment by magicsoft75** [comment]
.../el.py jest skryptem:
import datetime
import elicznik

with elicznik.ELicznik("xxx", "xxxx") as m:
    # date range
    print("July 2023")

    readings = m.get_readings(datetime.date(2023, 7, 1), datetime.date(2023, 7, 30))

    for timestamp, consumed, produced, A, B in readings:
        print(timestamp, consumed, produced, A, B)
....

Na razie na 8h dostałem bana (za dużo logowań) :-) więc sprawdzę jutro i dodam dwie dodatkowe wartości.

**Comment by magicsoft75** [comment]
Sprawdziłem. Z pięcioma parametrami działa.
Dziękuję

**Comment by mlesniew** [comment]
Super!
