### ISSUE TITLE
Wiesz może dlaczego korzystając z przykładu API dostaje takie coś:

### ISSUE THREAD

**Issue by mlesniew** [mlesniew/elicznik#17]
Wiesz może dlaczego korzystając z przykładu API dostaje takie coś:  
with elicznik.ELicznik("****", "****", "optional_site_identifier") as m:
AttributeError: partially initialized module 'elicznik' has no attribute 'ELicznik' (most likely due to a circular import)
jak w bashu wywołam komendę z loginem, hasłem i datą to jest ok...

_Originally posted by @g6pl in https://github.com/mlesniew/elicznik/issues/11#issuecomment-2391308122_

**Comment by mlesniew** [comment]
@g6pl zmień nazwę swojego skryptu z elicznik.py na inną.

**Comment by g6pl** [comment]
Dzięki brachu!
