### ISSUE TITLE
Uwaga na bany

### ISSUE THREAD

**Issue by jpomykala** [mlesniew/elicznik#18]
Wszystko działa fajnie ale po pobraniu około 2 miesięcy dostałem bana:

<img width="880" alt="image" src="https://github.com/user-attachments/assets/ab5400a0-46da-49b0-a62d-06c893beaf58" />

Sam jestem sobie winny bo pobierałem dzień po dniu zamiast pobrać przedział. 😵‍💫

**Comment by mlesniew** [comment]
Znany numer, na szczęście bana zdejmują automatycznie sami -- wystarczy poczekać :-)
