### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by blacksocket** [mlesniew/elicznik#2]
Hello,

I installed the elicznik and getting an error after launching the command below:
elicznik freddy@example.com mypasssword 2022-04-23

[1] 21298
-bash: 2022-04-23: command not found

but when launch the command "elicznik -h " it works fine, also api works  fine. I am using special characters in password like: . ? &

----------------------------------------------
bash: elicznik -h
usage: elicznik [-h] [--format {raw,table,csv}]
                username password [start date] [end date]

positional arguments:
  username              tauron-dystrybucja.pl user name
  password              tauron-dystrybucja.pl password
  start date            Start date of date range to be retrieved, in ISO8601
                        format. If the end date is omitted, it's the only date
                        for which measurements are retrieved.
  end date              End date of date range to be retrieved, inclusive, in
                        ISO8601 format. Can be omitted to only retrieve a
                        single day's measurements.

optional arguments:
  -h, --help            show this help message and exit
  --format {raw,table,csv}
                        Specify the output format

**Comment by mlesniew** [comment]
Most likely your password contains a special char, perhaps it ends with a semicolon, ampersand or pipe symbol?  This makes bash interpret the next parameter as a separate new command.

Try putting the login and password parameters in single quotes, e.g. `elicznik 'freddy@example.com' 'mypasssword' 2022-04-23`

**Comment by blacksocket** [comment]
Now its better however still getting error but this time:

Traceback (most recent call last):
  File "/home/pi/.local/bin/elicznik", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/elicznik/__main__.py", line 55, in main
    result = elicznik.get_readings(args.start_date, args.end_date)
AttributeError: 'Namespace' object has no attribute 'start_date'

**Comment by mlesniew** [comment]
That's a bug -- I fixed it in v1.2.
