### ISSUE TITLE
Przestało działać

### ISSUE THREAD

**Issue by jochym** [mlesniew/elicznik#3]
Niestety Tauron zmienił API i program przestał działać. Z tego, co widzę, zlikwidowali end-point /index/.
Strona odwołuje się do csv inaczej (inne argumenty w formularzu i chyba inny URL).
Czy pierwotna wersja korzystała z linku do danych csv na stronie?

**Comment by manio** [comment]
https://github.com/manio/elicznik-rs/issues/1
CSV umiem pobrać, ale w elicznik też jest pobierane metodą JSON, która sie "wywaliła".

**Comment by mlesniew** [comment]
Rzeczywiście, zmienili API.  Skrypt zawsze uderzał w endpoint zwracający dane jsonowe, konwersja na CSV przebiegała w samym skrypcie.

Zmiany API są dość proste, może uda mi się to naprawić

**Comment by mlesniew** [comment]
Fixnięte w [v1.3](https://github.com/mlesniew/elicznik/tree/v1.3).

**Comment by jochym** [comment]
Super. Dopisałem funkcję korzystającą z interface do pobierania danych — parsującą CSV. 
Nie jest skończona, bo mi zablokowali na 8 godzin. Ale przy ostatnim wywołaniu zadziałała.
Można zaglądnąć do https://github.com/jochym/elicznik jako źródło inspiracji ;)
Dodałem też pomysł na zapis parametrów, aby ominąć podawanie danych w linii poleceń.

**Comment by mlesniew** [comment]
@jochym Parsowanie CSV wygląda ciekawie, czy ten sposób ma przewagę nad rozwiązaniem z JSONem?  Jeśli tak, to może należałoby to włączyć do tego repo?  Jestem otwarty na PRy.  

Odnośnie parsowania CSV warto spróbować użyć do tego [wbudowanego modułu csv](https://docs.python.org/3/library/csv.html) zamiast robić to na piechotę.

**Comment by jochym** [comment]
Słusznie i naukowo. Przygotuję stosownego PR. Tylko musi mi się odblokować konto i muszę mieć chwilę, aby nad tym usiąść. W tej chwili jest to rozbabrane, bo blokada złapała mnie w środku eksperymentów. Myślę, że dodanie alternatywnej ścieżki może  być korzystne.

**Comment by adik015** [comment]
Hej, Tauron zmienił znowu cos z API? Skrypt przestał pobierać dane, nie zwraca błędu.

**Comment by manio** [comment]
Tak, u mnie też nie działa :(

Edit:
Mam nadzieje że to przejściowe, bo:

Na stronie logowania jest info:

> Serwisujemy się
> 
> Trwają prace serwisowe. Najważniejsze sprawy w serwisie i aplikacji Mój TAURON załatwisz tak jak do tej pory – m. in. sprawdzisz i zapłacisz fakturę, przepiszesz licznik lub zmienisz ofertę. Pełne funkcjonowanie serwisu przywrócimy 19 kwietnia.
> Przepraszamy za utrudnienia.
> 

a po próbie zalogowania jest:

> Nasz serwis internetowy jest tymczasowo niedostępny.
> 
> Przepraszamy za utrudnienia

Generalnie ja dostaję ze swojej aplikacji JSONy z danymi ale są one niepełne/jakieś dziwne.

**Comment by manio** [comment]
Strona tauron-dystrybucja jednak działa a API faktycznie zmieniło się w tym zakresie że struktura wynikowa JSON-a jest inna.

**Comment by adik015** [comment]
> Generalnie ja dostaję ze swojej aplikacji JSONy z danymi ale są one niepełne/jakieś dziwne.

Pobierasz te dane może skryptem w pythonie może? Mnie by nawet JSONy odpowiadały, tylko nie wiem jak to dostać z API taurona... kiedyś zacząłem analizować tą ich stronę ale się poddałem bo znalazłem wasze działające skrypty które trochę dostosowałem do siebie. Nie chce mi się koła na nowo odkrywać a wy już fajną robotę zrobiliście.

**Comment by manio** [comment]
Nie - na własne potrzeby napisałem parser i scraper w rust. Z tego co na szybko wczoraj przejrzałem to wyglada to tak, że tego JSON-a teraz bedzie chyba się źle analizować - kiedyś to było poukładane w jakieś sensowne "rekordy" - w każdym rekordzie była data i ilość energii - aktualnie chyba nawet nie ma żadnych dat - to wyglada jakby bardziej było dopasowane do tego javascripta robiącego wykres na stronie. Jeśli chodzi o mnie i mój kod to chyba przerzucę się na parsowanie CSV-a - bo te dane maja wiekszy sens i mam nadzieje ze nie będą w tym za dużo "kopać". Ale to temat odnośnie mojego programu - więc może nie róbmy tu off-topica...

**Comment by mlesniew** [comment]
Rzeczywiście, Tauron znowu zmienił API.  Zrobiłem odpowiednie poprawki i zrobiłem nowego rilisa. Poprawiona wersja jest na masterze i na [PyPI](https://pypi.org/project/elicznik/1.4.3/).

Wygląda na to, że Jsonowe API zmienia się dość często, może rzeczywiście warto raczej przejść domyślnie na to, które zwraca CSVki.  Skoro pliki CSV można pobierać ze strony, to można zakładać, że przynajmniej ich format się nie będzie zmieniał tak często.

@manio @adik015 zamknę to issue.  Jeśli napotkacie problemy z poprawioną wersją, możemy otworzyć je z powrotem.  Kiedy znowu API się zmieni, możemy założyć nowe, aby to nie ciągnęło się w nieskończoność.

**Comment by jochym** [comment]
Ja przeszedłem na CSV i jak dotąd nie było zacięć. Miałem zrobić PR, ale mam taki zap..., że się nie wyrabiam. Może za około tygodnia.
