### ISSUE TITLE
Kilka liczników na jednym koncie Tauron

### ISSUE THREAD

**Issue by tomekbee** [mlesniew/elicznik#5]
Skrypt poprawnie działa gdy do konta tauronu przypisany jest tylko 1 licznik - domyślnie brany jest pierwszy zarejestrowany. W przypadku posiadania kilku, należy po zalogowaniu wysłać request  przypisujący do sesji identyfikator licznika który nas interesuje:
self.session.post(
"https://elicznik.tauron-dystrybucja.pl/ustaw_punkt",
data={
"site[client]": "XXXXXXXX_YYYYYYYY_ZZZZZZZ"
},
)

"XXXXXXXX_YYYYYYYY_ZZZZZZZ" - identyfikator licznika

**Comment by janmyszkier** [comment]
Dziękuję @tomekbee , dodałem PR'a na ten temat, żeby każdy wiedział co z tym zrobić
https://github.com/mlesniew/elicznik/pull/12

gdyby ktoś miał problem ze znalezieniem numeru `site` to można go znaleźć następująco:
Podczas zmiany licznika w portalu e-licznik taurona, strona robi request do /ustaw_punkt z tym parametrem i można go sobie podejrzeć devtools przeglądarki w zakładce network

**Comment by mlesniew** [comment]
Zmiany które pozwalają na określenie licznika/punktu poboru są już na masterze oraz w najnowszym rilisie `2.2.0`.  Można go już zainstalować z PyPI. 

Wielkie dzięki dla @janmyszkier za dodanie tego ficzera.
