### ISSUE TITLE
Znowu coś zepsuli

### ISSUE THREAD

**Issue by jochym** [mlesniew/elicznik#7]
Chyba Tauron coś znowu pozmieniał, bo u mnie przestało działać (30/07 ostatni odczyt) a dane na portalu są. Niestety nie mam czasu przez kilka dni się tym zająć. Może ktoś (@mlesniew ?) zdoła na to spojrzeć/zweryfikować czy mam rację/naprawić.

**Comment by jochym** [comment]
Chyba fałszywy alarm. Błąd musi być w moim kodzie, bo `elicznik user pass` działa poprawnie. Zamykam issue w związku z tym.

**Comment by jochym** [comment]
Jednak zepsuli, tylko że częściowo. Mój synchronizator  używał metody `get_data` i ona przestała działać. `get_readings` nadal działa. Być może czas się pozbyć starej `get_data`? Szkoda energii na walkę z ich prywatnym API, skoro jest publiczne.

**Comment by manio** [comment]
Metoda pobierania pliku CSV/XLS też została lekko zmieniona. Zmienili `POST` na `GET` :D
Musiałem zrobić na szczęście drobną poprawkę i znowu działa...

**Comment by mlesniew** [comment]
Rzeczywiście, znowu były zmiany.  Zrobiłem poprawki i najnowsza wersja elicznika powinna działać -- jest już w PyPI.
